[package]
name = "openmetrics_udpserver"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]
edition = "2021"

[dependencies]
anyhow = "*"
clap = "4.4.*"
bytes = "1.5.*"
regex = "1.10.*"
actix-web = "4.4.*"
byteorder = "1.5.*"
prometheus-client = "0.21.*"
tokio = { version = "1.33.*", features = ["macros", "rt-multi-thread"] }
openmetrics_udpserver_lib = { path = "../openmetrics_udpserver_lib" }
